### PR TITLE
Add PHP8 support

### PR DESCRIPTION
**Pull request by godbout**

### CODE REVIEW

**Comment by godbout** [comment]
ok only seeing the issue now, so my PR might be dumb. all the tests ran through tho.

**Comment by godbout** [comment]
please close if it's dumb. i'm going to try to use the dev-php8 branch in my project.

**Comment by godbout** [comment]
ah. `dev-php8` doesn't exist anymore.

**Comment by ocean90** [comment]
Support for PHP 8 was already added in #30 but there's no new release yet.

**Pull request closed without merging**
