### PR TITLE
Add php-http/client-common to composer require

### PR DESCRIPTION
**Pull request by godbout**
Else you get a nice

```PHP Fatal error:  Interface 'Http\Client\Common\Plugin' not found in /Users/guill/Development/alfred-time/vendor/wearerequired/harvest-api-php-client/src/HttpClient/Plugin/ResponseExceptionThrower.php on line 23```

when using the package.

### CODE REVIEW

**Comment by ocean90** [comment]
Nice catch! It should be added to the `require` part in `composer.json`. Have to check if we can use `"^1.0 || ^2.0"` here too.

**Comment by godbout** [comment]
Oh. Makes sense. I'm not very familiar with all the different HTTP implementations, PSR7 blah blah blah so I just thought it was my responsibility to add it, not your package.

I'm using 2.0 and it works well! Thanks for your API.

**Comment by ocean90** [comment]
Thanks again @godbout, just published 0.1.1. Let us know if you find anything else.

**Comment by godbout** [comment]
API working great. Thanks for the awesome work!

**Pull request merged**
